### PR TITLE
Use the archive_url for all downloads

### PR DESCRIPTION
**Pull request by patcon**
https://github.com/bflad/chef-mysql_connector/blob/master/providers/j.rb

There seems to be lots going on here to get around the fact that the main download url changes, but why not just use the archive for everything. Even the newest tar is available there, so why not? :)

### CODE REVIEW

**Comment by patcon** [comment]
Done, and added the ark resource back in, since it now supports the strip-components flag that was missing before :)

I also removed an empty recipe, so hopefully that's not a problem

**Comment by dwmarshall** [comment]
Update `.travis.yml' to get Travis to build. See #12 for the change.

**Comment by patcon** [comment]
Good call. Let's just merge your first

**Comment by bflad** [comment]
Sweet. So glad to see this simplified again! Thank you. I merged #12, will cut the 0.7.4 release, then release this as 0.8.0 once I get this new laptop all squared away.

**Comment by patcon** [comment]
Rockin! Rebased on master

**Comment by patcon** [comment]
I think S3 is having issues, but should work by tomorrow

**Comment by bflad** [comment]
0.7.4 released - merging this and releasing 0.8.0 right now as well. Thanks for the PR!

**Comment by patcon** [comment]
:+1:

**Comment by bflad** [comment]
Are you sure this works for latest version? This has always been an issue (returns 404 on archives endpoint for latest version) and unless something is wonky this second in my testing, this still requires the direct Downloads link.

I'm refactoring the provider already so I'll take a stab at auto-detection still.

```
➜  chef-mysql_connector git:(master) ✗ curl -o /dev/null -v http://cdn.mysql.com/archives/mysql-connector-java-5.1/mysql-connector-java-5.1.35.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.64.66.140...
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to cdn.mysql.com (104.64.66.140) port 80 (#0)
> GET /archives/mysql-connector-java-5.1/mysql-connector-java-5.1.35.tar.gz HTTP/1.1
> Host: cdn.mysql.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Apache
< ETag: "e59c9438a9c6c07e27252ad3156123ca:1435849673"
< Last-Modified: Tue, 17 Mar 2015 07:18:56 GMT
< Accept-Ranges: bytes
< Content-Length: 3848304
< Date: Thu, 13 Aug 2015 03:40:22 GMT
< Connection: keep-alive
< Content-Type: application/x-tar-gz
<
{ [1448 bytes data]
100 3758k  100 3758k    0     0   119k      0  0:00:31  0:00:31 --:--:--  107k
* Connection #0 to host cdn.mysql.com left intact
➜  chef-mysql_connector git:(master) ✗ curl -o /dev/null -v http://cdn.mysql.com/archives/mysql-connector-java-5.1/mysql-connector-java-5.1.36.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.64.66.140...
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to cdn.mysql.com (104.64.66.140) port 80 (#0)
> GET /archives/mysql-connector-java-5.1/mysql-connector-java-5.1.36.tar.gz HTTP/1.1
> Host: cdn.mysql.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: Apache
< Content-Length: 16
< Date: Thu, 13 Aug 2015 03:41:09 GMT
< Connection: keep-alive
< Content-Type: application/x-tar-gz
<
{ [16 bytes data]
100    16  100    16    0     0     11      0  0:00:01  0:00:01 --:--:--    11
* Connection #0 to host cdn.mysql.com left intact
➜  chef-mysql_connector git:(master) ✗ curl -o /dev/null -v http://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-5.1.36.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.64.66.140...
* Connected to cdn.mysql.com (104.64.66.140) port 80 (#0)
> GET /Downloads/Connector-J/mysql-connector-java-5.1.36.tar.gz HTTP/1.1
> Host: cdn.mysql.com
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Apache
< ETag: "9a06f655da5d533a3c1b2565b76306c7:1435849207"
< Last-Modified: Thu, 25 Jun 2015 18:05:39 GMT
< Accept-Ranges: bytes
< Content-Length: 3888402
< Cache-Control: private, max-age=27950025
< Date: Thu, 13 Aug 2015 03:41:52 GMT
< Connection: keep-alive
< Content-Type: application/x-tar-gz
<
{ [1128 bytes data]
100 3797k  100 3797k    0     0   124k      0  0:00:30  0:00:30 --:--:--  185k
* Connection #0 to host cdn.mysql.com left intact
```

**Comment by dwmarshall** [comment]
I didn't verify the endpoints that the cookbook uses, unfortunately. I thought it was sufficient to update the checksums.

**Comment by bflad** [comment]
The next version of the cookbook will automatically test both URLs, achieving the original intent here.

**Comment by bflad** [comment]
I'm actually going to revert ark as well. Ark does not (re)place the jar file (because the download file exists) if you:
* add/modify install_paths
* remove the extracted file from any of the install_paths

Feel free to see the ark source code for reference (ugh with all the notifies not testing things): https://github.com/burtlo/ark/blob/master/providers/default.rb#L224-L243

**Comment by bflad** [comment]
0.8.1 released

**Pull request merged**
